# Generated by Django 5.0.1 on 2024-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_menucategory_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order'], 'verbose_name': 'Menu Category', 'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
